BlogApp/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria')
]

CarroApp/urls.py
from django.urls import path

from .import views

app_name = "CarroApp"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('ServiciosApp.urls')),
    path('blog/', include('BlogApp.urls')),
    path('contacto/', include('ContactoApp.urls')),
    path('tienda/', include('TiendaApp.urls')),
    path('carro/', include('CarroApp.urls')),
    path('autenticacion/', include('AutenticacionApp.urls')),
    path('pedidos/', include('PedidosApp.urls')),
]

TiendaApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.tienda, name='Tienda'),
]

TiendaApp/models.py
from django.db import models

# Create your models here.



class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriaProd'
        verbose_name_plural = 'categoriasProd'

    def __str__(self):
        return self.nombre
    


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='TiendaApp', null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

TiendaApp/views.py
from django.shortcuts import render

from TiendaApp.models import Producto, CategoriaProd

# Create your views here.

def tienda(request):

    productos = Producto.objects.all()

    return render(request, "tienda/tienda.html", {"productos": productos})

TiendaApp/templates/carro/widget.html
{% load static %}

{% block extra_css %}
  <link href="{% static 'ProyectoWebApp/css/gestionTiendaApp.css' %}" rel="stylesheet">
{% endblock %}

<table class="table table-bordered" class="carro-container" style="color: white; background-color: rgb(57, 72, 103); max-height: 900px; overflow-y: auto;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Total</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'CarroApp:agregar' value.producto_id %}" class="r btn btn-sm btn-success">+</a>
                        <a href="{% url 'CarroApp:restar' value.producto_id %}" class="r btn btn-sm btn-success" style="background-color: red; border: red;">-</a><br/>
                        ${{value.precio}} 
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-center">
                Total: {{importe_total_carro}} $
            </td>
        </tr>
        {% if request.session.carro.items %}
            <tr>
                <td colspan="3" class="text-center">
                    <a href="{% url 'procesar_pedido' %}" class="btn btn-success">Realizar pedido</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>

</table>